### ISSUE TITLE
安装完 启动项目报错

### ISSUE THREAD

**Issue by hellobluefat** [xpyjs/gantt-vue2#11]
app.js:3009 Uncaught TypeError: (0 , a.defineComponent) is not a function
    at app.js:3009:200815
    at app.js:3009:233997
    at app.js:3009:234017
    at app.js:3009:37
    at ./node_modules/.store/@xpyjs+gantt-vue2@1.0.4/node_modules/@xpyjs/gantt-vue2/lib/index.umd.min.js (app.js:3009:266)
    at __webpack_require__ (app.js:679:30)
    at fn (app.js:89:20)
    at ./src/main.js (app.js:108533:77)
    at __webpack_require__ (app.js:679:30)
    at fn (app.js:89:20)

**Comment by jeremyjone** [comment]
检查你的版本

**Comment by hellobluefat** [comment]
![微信图片_20240719113423](https://github.com/user-attachments/assets/2bebdfe4-80c3-44d8-b0c5-dbe1a14cb8e4)
大佬 我的vue 和 vue-template-compiler 都固定版本 2.6.14了

**Comment by jeremyjone** [comment]
很久不用了，有时间我看看
